-- AI-generated custom elements for the template editor (charts, tables, candlesticks, metric cards, …).
-- Each is an isolated canvas draw-function (its BODY stored as `code`), generated by the "Build with AI"
-- panel and saved per user — like a custom automation node, but its "execution" is a canvas render.
-- See production/AI_ELEMENTS_DESIGN.md. Safe to re-run.
-- Run in: Supabase Dashboard → SQL Editor.

create table if not exists public.custom_elements (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  name          text not null default 'Untitled element',
  description   text not null default '',
  code          text not null default '',          -- render-function body: (ctx, props) => void
  input_schema  jsonb not null default '[]'::jsonb, -- ElementInput[] (data "ports"); [] = static element
  default_data  jsonb,                              -- sample data so it renders before a node is bound
  size          jsonb not null default '{}'::jsonb, -- { w, h, aspect } default box (canvas px / ratio)
  thumbnail_url text,                               -- optional rendered preview
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists custom_elements_user_idx on public.custom_elements(user_id, updated_at desc);

alter table public.custom_elements enable row level security;

drop policy if exists "custom_elements: owner read"   on public.custom_elements;
drop policy if exists "custom_elements: owner insert" on public.custom_elements;
drop policy if exists "custom_elements: owner update" on public.custom_elements;
drop policy if exists "custom_elements: owner delete" on public.custom_elements;

create policy "custom_elements: owner read"   on public.custom_elements for select to authenticated using (user_id = auth.uid());
create policy "custom_elements: owner insert" on public.custom_elements for insert to authenticated with check (user_id = auth.uid());
create policy "custom_elements: owner update" on public.custom_elements for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "custom_elements: owner delete" on public.custom_elements for delete to authenticated using (user_id = auth.uid());
